AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: smartwallet-users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GeolocationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: smartwallet-geolocation
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SmartWalletLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GEOLOCATION_TABLE: !Ref GeolocationTable
          JWT_SECRET: !Ref JWTSecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GeolocationTable
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post

  SmartWalletRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: register.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /register
            Method: post

Parameters:
  JWTSecret:
    Type: String
    Description: JWT secret key
    NoEcho: true

Outputs:
  LoginApiUrl:
    Description: Login API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login"
  RegisterApiUrl:
    Description: Register API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register"