AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SmartWalletLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDBURI
          JWT_SECRET: !Ref JWTSecret
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post

Parameters:
  MongoDBURI:
    Type: String
    Description: MongoDB connection string
  JWTSecret:
    Type: String
    Description: JWT secret key
    NoEcho: true

Outputs:
  LoginApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login"